name: Remove KSU Folder (Submodule)

on:
  workflow_dispatch:
  push:
    branches:
      - ASB-2024-10-05

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ASB-2024-10-05
          fetch-depth: 0

      - name: Remove old KSU
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "you-github"
          git rm -r KernelSU || rm -rf KernelSU
          git commit -m "Remove old KSU"
          git pull --rebase origin ASB-2024-10-05
          git push origin ASB-2024-10-05
